const names=["Sárkánygyümölcs","Citrom","Csoki","Dinnye","Banán","Oreo","Rágógumi","Vattacukor"];
const c=document.getElementById("flavors");
names.forEach((n,i)=>c.innerHTML+=`<label>${n}<input type="number" id="m${i}"></label>`);
const val=id=>Number(document.getElementById(id).value)||0;
document.querySelectorAll("input").forEach(i=>i.addEventListener("wheel",e=>e.preventDefault(),{passive:false}));
document.getElementById("calc").onclick=()=>{
 let current=0;
 for(let i=0;i<8;i++) current+=val("m"+i);
 const yesterday=val("yesterdayTotal")+val("extra");
 const expected=val("l")*60+val("xl")*80+val("xxl")*100+val("cs")*240;
 const actual=yesterday-current;
 const diff=actual-expected;
 const cups=val("l")+val("xl")+val("xxl")+val("cs");
 const avg=cups?Math.abs(diff)/cups:0;
 expectedEl.textContent=expected+" g";
 actualEl.textContent=actual+" g";
 diffEl.textContent=(diff>0?"+":"")+diff+" g";
 const a=document.getElementById("avg");
 a.textContent=avg.toFixed(2)+" g/pohár";
 a.className="";
 if(avg<1.5)a.classList.add("pink");
 else if(avg<2.2)a.classList.add("blue");
 else if(avg<2.8)a.classList.add("green");
 else if(avg<3.2)a.classList.add("yellow");
 else a.classList.add("red");
 result.classList.remove("hidden");
};
const expectedEl=document.getElementById("expected");
const actualEl=document.getElementById("actual");
const diffEl=document.getElementById("diff");
const result=document.getElementById("result");
